#!/usr/bin/env bash
# Install pip3 Packages
pip3 install -r requirements.txt

# BUILD=Variable denoting current build string:
BUILD=`date -u +"%D-%T"`
BUILD="$BUILD-`whoami`"

echo $BUILD >> BUILD.txt

# Build Elm frontend
elm make --output=output/main.js --optimize src/Main.elm

# Start Server
gunicorn main:app
