# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler/blob/master/README.md

name: Labeler
on: [pull_request]

critical:
  - output/login.html
  - output/vote.html
  - main.py
  - Server/election.py
  - Server/Elections.py
  - Server/test_election.py
  - Server/Crypto/*
  
patches:
  - Server/Patches.py
  - Server/patch.sh

elections:
  - output/vote.html
  - Server/election.py
  - Server/Elections.py
  - Server/test_election.py

crypto:
  - Server/Crypto/*

users:
  - Server/Users.py

running-building:
  - start


jobs:
  label:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/labeler@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
